input {
  kafka {
    bootstrap_servers => "${BOOTSTRAP_SERVER}"
    client_id         => "store"
    group_id          => "store"
    topics            => ["${TOPIC_PROCESSED}"]
    codec             => json
  }
}

filter {

  if ![ID] {
    uuid {
      target => "ID"
    }
  }

  if ![Version] {
    mutate {
      replace => {
        '[Version]' => '2.D.V08'
      }
    }
  }

  if ![Target][0][Location] {
    mutate {
      add_field => {
        '[Target][0][Location]' => 'Data Center'
      }
    }
  }

  ruby {
    path => "/usr/share/logstash/config/scripts/normalize_array.rb"
    script_params => {
      "fields" => [
        "Attachment",
        "Target",
        "Source",
        "Sensor",
        "EntitySector",
        "Type",
        "Category",
        "ext-Category",
        "Status",
        "AltNames",
        "AltCategory",
        "Ref",
        "CorrelID",
        "AggrCondition",
        "PredID",
        "RelID"
      ]
    }
  }

  ruby {
    path => "/usr/share/logstash/config/scripts/manage_predid.rb"
    script_params => {
      "es_url" => "${BIG_DATA_SERVER}${INDEX_ALERTS}/_update_by_query"
      "username" => "${BIG_DATA_USERNAME}"
      "password" => "${BIG_DATA_PASSWORD}"
    }
  }


  prune {
    whitelist_names => [
      # Top-level IDMEF attributes
      'Version',
      'ID',
      'OrganisationName',
      'OrganisationId',
      'EntityName',
      'EntityId',
      'EntitySector',
      'Type',
      'Category',
      'ext-Category',
      'Cause',
      'Description',
      'Status',
      'Priority',
      'Confidence',
      'Note',
      'CreateTime',
      'StartTime',
      'EndTime',
      'ReportTime',
      'AltNames',
      'AltCategory',
      'Ref',
      'CorrelID',
      'AggrCondition',
      'PredID',
      'RelID',

      # IDMEF classes
      'Analyzer',
      'Sensor',
      'Source',
      'Target',
      'Attachment'
    ]
  }

}

output {

  elasticsearch {
    hosts              => ["${BIG_DATA_SERVER}"]
    user               => "${BIG_DATA_USERNAME}"
    password           => "${BIG_DATA_PASSWORD}"
    template_api       => "legacy"
    ilm_enabled        => false
    #ilm_rollover_alias => "${INDEX_ALERTS}"
    template_overwrite => true
    template           => "/usr/share/logstash/config/IDMEFv2.mapping"
    manage_template    => true
    template_name      => "alert"
    #index              => "${INDEX_ALERTS}-%{+yyyy.MM.dd}"
    index              => "${INDEX_ALERTS}"
  }
}
