apiVersion: v1
kind: Service
metadata:
  name: logstash
  labels:
    app: logstash-service
spec:
  type: NodePort
  ports:
    - port: 4690
      name: logstash-tcp-4690
      nodePort: 30345
      protocol: TCP
    - port: 6514
      name: logstash-tcp-6514
      nodePort: 30514
      protocol: TCP
    - port: 6514
      name: logstash-udp-6514
      nodePort: 30514
      protocol: UDP
  selector:
    app: logstash-tmpl
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: logstash
  labels:
    app: logstash-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logstash-tmpl
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: logstash-tmpl
    spec:
      containers:
      - image: idmefv2prototype/logstash:main
        name: logstash
        resources:
          limits:
            cpu: "4000m"
        env:
        - name: LS_JAVA_OPTS
          value: "-Xms4g -Xmx4g -Xss256k"
        - name: LOGSTASH_INTERNAL_PASSWORD
          value: ""
        - name: MONITORING_ENABLED
          value: "false"
        - name: MAX_MSG_SIZE
          value: "1048576"
        - name: BOOTSTRAP_SERVER
          value: "http://kafka:9092"
        - name: BIG_DATA_SERVER
          value: "http://es01:9200/"
        - name: BIG_DATA_USERNAME
          value: "elastic"
        - name: BIG_DATA_PASSWORD
          value: "elastic"
        - name: ANALYZER_NAME
          value: "Logstash"
        - name: ANALYZER_LOCATION
          value: "Safe4SOC - Prototype"
        - name: ANALYZER_UNLOCATION
          value: "FR PAR"
        - name: ANALYZER_GEOLOCATION
          value: "48.7730817, 2.2442167"
        - name: ANALYZER_IP
          value: "192.168.1.1"
        - name: ANALYZER_HOSTNAME
          value: "fedora"
        - name: LISTEN_SYSLOG
          value: "6514"
        - name: LISTEN_HTTP
          value: "4690"
        - name: TOPIC_COLLECTED
          value: "my_collected"
        - name: TOPIC_PROCESSED
          value: "my_processed"
        - name: INDEX_ALERTS
          value: "alerts"
        - name: INDEX_LOGS
          value: "logs"
        ports:
        - containerPort: 6514
          name: logstash-6514
        - containerPort: 4690
          name: logstash-4690
        volumeMounts:
          - name: config
            mountPath: /usr/share/logstash/config/logstash.yml
            subPath: config/logstash.yml
          - name: config
            mountPath: /usr/share/logstash/config/jvm.options
            subPath: config/jvm.options
          - name: config
            mountPath: /usr/share/logstash/config/pipelines.yml
            subPath: pipelines.yml
          - name: config
            mountPath: /usr/share/logstash/config/rules.yml
            subPath: rules.yml
          - name: config
            mountPath: /usr/share/logstash/config/IDMEFv2-light.schema
            subPath: IDMEFv2-light.schema
          - name: config
            mountPath: /usr/share/logstash/config/IDMEFv2.schema
            subPath: IDMEFv2.schema
          - name: config
            mountPath: /usr/share/logstash/config/IDMEFv2.mapping
            subPath: IDMEFv2.mapping
          - name: config
            mountPath: /usr/share/logstash/config/NXLog.schema
            subPath: NXLog.schema
          - name: config
            mountPath: /usr/share/logstash/config/pipeline
            subPath: pipeline
          - name: config
            mountPath: /usr/share/logstash/config/scripts
            subPath: scripts
          - name: config
            mountPath: /usr/share/logstash/config/rulesets
            subPath: rulesets
          - name: config
            mountPath: /usr/share/logstash/config/to_idmef
            subPath: to_idmef
      volumes:
      - name: config
        hostPath:
          path: /mnt/minikube/logstash
          type: Directory
